export const COUNTRY_LIST = [
  {
    name: "Singapore",
    alpha2Code: "SG",
    alpha3Code: "SGP",
    flag: "assets/flags/Singapore.svg",
    code: "+65",
  },
  {
    name: "Malaysia",
    alpha2Code: "MY",
    alpha3Code: "MYS",
    flag: "assets/flags/Malaysia.svg",
    code: "+60",
  },
  {
    name: "Afghanistan",
    alpha2Code: "AF",
    alpha3Code: "AFG",
    flag: "assets/flags/Afghanistan.svg",
    code: "+93",
  },
  {
    name: "Åland Islands",
    alpha2Code: "AX",
    alpha3Code: "ALA",
    flag: "assets/flags/Åland Islands.svg",
    code: "+358",
  },
  {
    name: "Albania",
    alpha2Code: "AL",
    alpha3Code: "ALB",
    flag: "assets/flags/Albania.svg",
    code: "+355",
  },
  {
    name: "Algeria",
    alpha2Code: "DZ",
    alpha3Code: "DZA",
    flag: "assets/flags/Algeria.svg",
    code: "+213",
  },
  {
    name: "American Samoa",
    alpha2Code: "AS",
    alpha3Code: "ASM",
    flag: "assets/flags/American Samoa.svg",
    code: "+1684",
  },
  {
    name: "Andorra",
    alpha2Code: "AD",
    alpha3Code: "AND",
    flag: "assets/flags/Andorra.svg",
    code: "+376",
  },
  {
    name: "Angola",
    alpha2Code: "AO",
    alpha3Code: "AGO",
    flag: "assets/flags/Angola.svg",
    code: "+244",
  },
  {
    name: "Anguilla",
    alpha2Code: "AI",
    alpha3Code: "AIA",
    flag: "assets/flags/Anguilla.svg",
    code: "+1264",
  },
  {
    name: "Antarctica",
    alpha2Code: "AQ",
    alpha3Code: "ATA",
    flag: "assets/flags/Antarctica.svg",
    code: "+672",
  },
  {
    name: "Antigua and Barbuda",
    alpha2Code: "AG",
    alpha3Code: "ATG",
    flag: "assets/flags/Antigua and Barbuda.svg",
    code: "+1268",
  },
  {
    name: "Argentina",
    alpha2Code: "AR",
    alpha3Code: "ARG",
    flag: "assets/flags/Argentina.svg",
    code: "+54",
  },
  {
    name: "Armenia",
    alpha2Code: "AM",
    alpha3Code: "ARM",
    flag: "assets/flags/Armenia.svg",
    code: "+374",
  },
  {
    name: "Aruba",
    alpha2Code: "AW",
    alpha3Code: "ABW",
    flag: "assets/flags/Aruba.svg",
    code: "+297",
  },
  {
    name: "Australia",
    alpha2Code: "AU",
    alpha3Code: "AUS",
    flag: "assets/flags/Australia.svg",
    code: "+61",
  },
  {
    name: "Austria",
    alpha2Code: "AT",
    alpha3Code: "AUT",
    flag: "assets/flags/Austria.svg",
    code: "+43",
  },
  {
    name: "Azerbaijan",
    alpha2Code: "AZ",
    alpha3Code: "AZE",
    flag: "assets/flags/Azerbaijan.svg",
    code: "+994",
  },
  {
    name: "Bahamas",
    alpha2Code: "BS",
    alpha3Code: "BHS",
    flag: "assets/flags/Bahamas.svg",
    code: "+1242",
  },
  {
    name: "Bahrain",
    alpha2Code: "BH",
    alpha3Code: "BHR",
    flag: "assets/flags/Bahrain.svg",
    code: "+973",
  },
  {
    name: "Bangladesh",
    alpha2Code: "BD",
    alpha3Code: "BGD",
    flag: "assets/flags/Bangladesh.svg",
    code: "+880",
  },
  {
    name: "Barbados",
    alpha2Code: "BB",
    alpha3Code: "BRB",
    flag: "assets/flags/Barbados.svg",
    code: "+1246",
  },
  {
    name: "Belarus",
    alpha2Code: "BY",
    alpha3Code: "BLR",
    flag: "assets/flags/Belarus.svg",
    code: "+375",
  },
  {
    name: "Belgium",
    alpha2Code: "BE",
    alpha3Code: "BEL",
    flag: "assets/flags/Belgium.svg",
    code: "+32",
  },
  {
    name: "Belize",
    alpha2Code: "BZ",
    alpha3Code: "BLZ",
    flag: "assets/flags/Belize.svg",
    code: "+501",
  },
  {
    name: "Benin",
    alpha2Code: "BJ",
    alpha3Code: "BEN",
    flag: "assets/flags/Benin.svg",
    code: "+229",
  },
  {
    name: "Bermuda",
    alpha2Code: "BM",
    alpha3Code: "BMU",
    flag: "assets/flags/Bermuda.svg",
    code: "+1441",
  },
  {
    name: "Bhutan",
    alpha2Code: "BT",
    alpha3Code: "BTN",
    flag: "assets/flags/Bhutan.svg",
    code: "+975",
  },
  {
    name: "Bolivia (Plurinational State of)",
    alpha2Code: "BO",
    alpha3Code: "BOL",
    flag: "assets/flags/Bolivia (Plurinational State of).svg",
    code: "+591",
  },
  {
    name: "Bonaire, Sint Eustatius and Saba",
    alpha2Code: "BQ",
    alpha3Code: "BES",
    flag: "assets/flags/Bonaire, Sint Eustatius and Saba.svg",
    code: "+5997",
  },
  {
    name: "Bosnia and Herzegovina",
    alpha2Code: "BA",
    alpha3Code: "BIH",
    flag: "assets/flags/Bosnia and Herzegovina.svg",
    code: "+387",
  },
  {
    name: "Botswana",
    alpha2Code: "BW",
    alpha3Code: "BWA",
    flag: "assets/flags/Botswana.svg",
    code: "+267",
  },
  {
    name: "Bouvet Island",
    alpha2Code: "BV",
    alpha3Code: "BVT",
    flag: "assets/flags/Bouvet Island.svg",
    code: "+0055",
  },
  {
    name: "Brazil",
    alpha2Code: "BR",
    alpha3Code: "BRA",
    flag: "assets/flags/Brazil.svg",
    code: "+55",
  },
  {
    name: "British Indian Ocean Territory",
    alpha2Code: "IO",
    alpha3Code: "IOT",
    flag: "assets/flags/British Indian Ocean Territory.svg",
    code: "+246",
  },
  {
    name: "United States Minor Outlying Islands",
    alpha2Code: "UM",
    alpha3Code: "UMI",
    flag: "assets/flags/United States Minor Outlying Islands.svg",
    code: "+246",
  },
  {
    name: "Virgin Islands (British)",
    alpha2Code: "VG",
    alpha3Code: "VGB",
    flag: "assets/flags/Virgin Islands (British).svg",
    code: "+1284",
  },
  {
    name: "Virgin Islands (U.S.)",
    alpha2Code: "VI",
    alpha3Code: "VIR",
    flag: "assets/flags/Virgin Islands (U.S.).svg",
    code: "+1 340",
  },
  {
    name: "Brunei Darussalam",
    alpha2Code: "BN",
    alpha3Code: "BRN",
    flag: "assets/flags/Brunei Darussalam.svg",
    code: "+673",
  },
  {
    name: "Bulgaria",
    alpha2Code: "BG",
    alpha3Code: "BGR",
    flag: "assets/flags/Bulgaria.svg",
    code: "+359",
  },
  {
    name: "Burkina Faso",
    alpha2Code: "BF",
    alpha3Code: "BFA",
    flag: "assets/flags/Burkina Faso.svg",
    code: "+226",
  },
  {
    name: "Burundi",
    alpha2Code: "BI",
    alpha3Code: "BDI",
    flag: "assets/flags/Burundi.svg",
    code: "+257",
  },
  {
    name: "Cambodia",
    alpha2Code: "KH",
    alpha3Code: "KHM",
    flag: "assets/flags/Cambodia.svg",
    code: "+855",
  },
  {
    name: "Cameroon",
    alpha2Code: "CM",
    alpha3Code: "CMR",
    flag: "assets/flags/Cameroon.svg",
    code: "+237",
  },
  {
    name: "Canada",
    alpha2Code: "CA",
    alpha3Code: "CAN",
    flag: "assets/flags/Canada.svg",
    code: "+1",
  },
  {
    name: "Cabo Verde",
    alpha2Code: "CV",
    alpha3Code: "CPV",
    flag: "assets/flags/Cabo Verde.svg",
    code: "+238",
  },
  {
    name: "Cayman Islands",
    alpha2Code: "KY",
    alpha3Code: "CYM",
    flag: "assets/flags/Cayman Islands.svg",
    code: "+1345",
  },
  {
    name: "Central African Republic",
    alpha2Code: "CF",
    alpha3Code: "CAF",
    flag: "assets/flags/Central African Republic.svg",
    code: "+236",
  },
  {
    name: "Chad",
    alpha2Code: "TD",
    alpha3Code: "TCD",
    flag: "assets/flags/Chad.svg",
    code: "+235",
  },
  {
    name: "Chile",
    alpha2Code: "CL",
    alpha3Code: "CHL",
    flag: "assets/flags/Chile.svg",
    code: "+56",
  },
  {
    name: "China",
    alpha2Code: "CN",
    alpha3Code: "CHN",
    flag: "assets/flags/China.svg",
    code: "+86",
  },
  {
    name: "Christmas Island",
    alpha2Code: "CX",
    alpha3Code: "CXR",
    flag: "assets/flags/Christmas Island.svg",
    code: "+61",
  },
  {
    name: "Cocos (Keeling) Islands",
    alpha2Code: "CC",
    alpha3Code: "CCK",
    flag: "assets/flags/Cocos (Keeling) Islands.svg",
    code: "+61",
  },
  {
    name: "Colombia",
    alpha2Code: "CO",
    alpha3Code: "COL",
    flag: "assets/flags/Colombia.svg",
    code: "+57",
  },
  {
    name: "Comoros",
    alpha2Code: "KM",
    alpha3Code: "COM",
    flag: "assets/flags/Comoros.svg",
    code: "+269",
  },
  {
    name: "Congo",
    alpha2Code: "CG",
    alpha3Code: "COG",
    flag: "assets/flags/Congo.svg",
    code: "+242",
  },
  {
    name: "Congo (Democratic Republic of the)",
    alpha2Code: "CD",
    alpha3Code: "COD",
    flag: "assets/flags/Congo (Democratic Republic of the).svg",
    code: "+243",
  },
  {
    name: "Cook Islands",
    alpha2Code: "CK",
    alpha3Code: "COK",
    flag: "assets/flags/Cook Islands.svg",
    code: "+682",
  },
  {
    name: "Costa Rica",
    alpha2Code: "CR",
    alpha3Code: "CRI",
    flag: "assets/flags/Costa Rica.svg",
    code: "+506",
  },
  {
    name: "Croatia",
    alpha2Code: "HR",
    alpha3Code: "HRV",
    flag: "assets/flags/Croatia.svg",
    code: "+385",
  },
  {
    name: "Cuba",
    alpha2Code: "CU",
    alpha3Code: "CUB",
    flag: "assets/flags/Cuba.svg",
    code: "+53",
  },
  {
    name: "Curaçao",
    alpha2Code: "CW",
    alpha3Code: "CUW",
    flag: "assets/flags/Curaçao.svg",
    code: "+599",
  },
  {
    name: "Cyprus",
    alpha2Code: "CY",
    alpha3Code: "CYP",
    flag: "assets/flags/Cyprus.svg",
    code: "+357",
  },
  {
    name: "Czech Republic",
    alpha2Code: "CZ",
    alpha3Code: "CZE",
    flag: "assets/flags/Czech Republic.svg",
    code: "+420",
  },
  {
    name: "Denmark",
    alpha2Code: "DK",
    alpha3Code: "DNK",
    flag: "assets/flags/Denmark.svg",
    code: "+45",
  },
  {
    name: "Djibouti",
    alpha2Code: "DJ",
    alpha3Code: "DJI",
    flag: "assets/flags/Djibouti.svg",
    code: "+253",
  },
  {
    name: "Dominica",
    alpha2Code: "DM",
    alpha3Code: "DMA",
    flag: "assets/flags/Dominica.svg",
    code: "+1767",
  },
  {
    name: "Dominican Republic",
    alpha2Code: "DO",
    alpha3Code: "DOM",
    flag: "assets/flags/Dominican Republic.svg",
    code: "+1809",
  },
  {
    name: "Ecuador",
    alpha2Code: "EC",
    alpha3Code: "ECU",
    flag: "assets/flags/Ecuador.svg",
    code: "+593",
  },
  {
    name: "Egypt",
    alpha2Code: "EG",
    alpha3Code: "EGY",
    flag: "assets/flags/Egypt.svg",
    code: "+20",
  },
  {
    name: "El Salvador",
    alpha2Code: "SV",
    alpha3Code: "SLV",
    flag: "assets/flags/El Salvador.svg",
    code: "+503",
  },
  {
    name: "Equatorial Guinea",
    alpha2Code: "GQ",
    alpha3Code: "GNQ",
    flag: "assets/flags/Equatorial Guinea.svg",
    code: "+240",
  },
  {
    name: "Eritrea",
    alpha2Code: "ER",
    alpha3Code: "ERI",
    flag: "assets/flags/Eritrea.svg",
    code: "+291",
  },
  {
    name: "Estonia",
    alpha2Code: "EE",
    alpha3Code: "EST",
    flag: "assets/flags/Estonia.svg",
    code: "+372",
  },
  {
    name: "Ethiopia",
    alpha2Code: "ET",
    alpha3Code: "ETH",
    flag: "assets/flags/Ethiopia.svg",
    code: "+251",
  },
  {
    name: "Falkland Islands (Malvinas)",
    alpha2Code: "FK",
    alpha3Code: "FLK",
    flag: "assets/flags/Falkland Islands (Malvinas).svg",
    code: "+500",
  },
  {
    name: "Faroe Islands",
    alpha2Code: "FO",
    alpha3Code: "FRO",
    flag: "assets/flags/Faroe Islands.svg",
    code: "+298",
  },
  {
    name: "Fiji",
    alpha2Code: "FJ",
    alpha3Code: "FJI",
    flag: "assets/flags/Fiji.svg",
    code: "+679",
  },
  {
    name: "Finland",
    alpha2Code: "FI",
    alpha3Code: "FIN",
    flag: "assets/flags/Finland.svg",
    code: "+358",
  },
  {
    name: "France",
    alpha2Code: "FR",
    alpha3Code: "FRA",
    flag: "assets/flags/France.svg",
    code: "+33",
  },
  {
    name: "French Guiana",
    alpha2Code: "GF",
    alpha3Code: "GUF",
    flag: "assets/flags/French Guiana.svg",
    code: "+594",
  },
  {
    name: "French Polynesia",
    alpha2Code: "PF",
    alpha3Code: "PYF",
    flag: "assets/flags/French Polynesia.svg",
    code: "+689",
  },
  {
    name: "French Southern Territories",
    alpha2Code: "TF",
    alpha3Code: "ATF",
    flag: "assets/flags/French Southern Territories.svg",
    code: "+262",
  },
  {
    name: "Gabon",
    alpha2Code: "GA",
    alpha3Code: "GAB",
    flag: "assets/flags/Gabon.svg",
    code: "+241",
  },
  {
    name: "Gambia",
    alpha2Code: "GM",
    alpha3Code: "GMB",
    flag: "assets/flags/Gambia.svg",
    code: "+220",
  },
  {
    name: "Georgia",
    alpha2Code: "GE",
    alpha3Code: "GEO",
    flag: "assets/flags/Georgia.svg",
    code: "+995",
  },
  {
    name: "Germany",
    alpha2Code: "DE",
    alpha3Code: "DEU",
    flag: "assets/flags/Germany.svg",
    code: "+49",
  },
  {
    name: "Ghana",
    alpha2Code: "GH",
    alpha3Code: "GHA",
    flag: "assets/flags/Ghana.svg",
    code: "+233",
  },
  {
    name: "Gibraltar",
    alpha2Code: "GI",
    alpha3Code: "GIB",
    flag: "assets/flags/Gibraltar.svg",
    code: "+350",
  },
  {
    name: "Greece",
    alpha2Code: "GR",
    alpha3Code: "GRC",
    flag: "assets/flags/Greece.svg",
    code: "+30",
  },
  {
    name: "Greenland",
    alpha2Code: "GL",
    alpha3Code: "GRL",
    flag: "assets/flags/Greenland.svg",
    code: "+299",
  },
  {
    name: "Grenada",
    alpha2Code: "GD",
    alpha3Code: "GRD",
    flag: "assets/flags/Grenada.svg",
    code: "+1473",
  },
  {
    name: "Guadeloupe",
    alpha2Code: "GP",
    alpha3Code: "GLP",
    flag: "assets/flags/Guadeloupe.svg",
    code: "+590",
  },
  {
    name: "Guam",
    alpha2Code: "GU",
    alpha3Code: "GUM",
    flag: "assets/flags/Guam.svg",
    code: "+1671",
  },
  {
    name: "Guatemala",
    alpha2Code: "GT",
    alpha3Code: "GTM",
    flag: "assets/flags/Guatemala.svg",
    code: "+502",
  },
  {
    name: "Guernsey",
    alpha2Code: "GG",
    alpha3Code: "GGY",
    flag: "assets/flags/Guernsey.svg",
    code: "+44",
  },
  {
    name: "Guinea",
    alpha2Code: "GN",
    alpha3Code: "GIN",
    flag: "assets/flags/Guinea.svg",
    code: "+224",
  },
  {
    name: "Guinea-Bissau",
    alpha2Code: "GW",
    alpha3Code: "GNB",
    flag: "assets/flags/Guinea-Bissau.svg",
    code: "+245",
  },
  {
    name: "Guyana",
    alpha2Code: "GY",
    alpha3Code: "GUY",
    flag: "assets/flags/Guyana.svg",
    code: "+592",
  },
  {
    name: "Haiti",
    alpha2Code: "HT",
    alpha3Code: "HTI",
    flag: "assets/flags/Haiti.svg",
    code: "+509",
  },
  {
    name: "Heard Island and McDonald Islands",
    alpha2Code: "HM",
    alpha3Code: "HMD",
    flag: "assets/flags/Heard Island and McDonald Islands.svg",
    code: "+672",
  },
  {
    name: "Holy See",
    alpha2Code: "VA",
    alpha3Code: "VAT",
    flag: "assets/flags/Holy See.svg",
    code: "+379",
  },
  {
    name: "Honduras",
    alpha2Code: "HN",
    alpha3Code: "HND",
    flag: "assets/flags/Honduras.svg",
    code: "+504",
  },
  {
    name: "Hong Kong",
    alpha2Code: "HK",
    alpha3Code: "HKG",
    flag: "assets/flags/Hong Kong.svg",
    code: "+852",
  },
  {
    name: "Hungary",
    alpha2Code: "HU",
    alpha3Code: "HUN",
    flag: "assets/flags/Hungary.svg",
    code: "+36",
  },
  {
    name: "Iceland",
    alpha2Code: "IS",
    alpha3Code: "ISL",
    flag: "assets/flags/Iceland.svg",
    code: "+354",
  },
  {
    name: "India",
    alpha2Code: "IN",
    alpha3Code: "IND",
    flag: "assets/flags/India.svg",
    code: "+91",
  },
  {
    name: "Indonesia",
    alpha2Code: "ID",
    alpha3Code: "IDN",
    flag: "assets/flags/Indonesia.svg",
    code: "+62",
  },
  {
    name: "Côte d'Ivoire",
    alpha2Code: "CI",
    alpha3Code: "CIV",
    flag: "assets/flags/Côte d'Ivoire.svg",
    code: "+225",
  },
  {
    name: "Iran (Islamic Republic of)",
    alpha2Code: "IR",
    alpha3Code: "IRN",
    flag: "assets/flags/Iran (Islamic Republic of).svg",
    code: "+98",
  },
  {
    name: "Iraq",
    alpha2Code: "IQ",
    alpha3Code: "IRQ",
    flag: "assets/flags/Iraq.svg",
    code: "+964",
  },
  {
    name: "Ireland",
    alpha2Code: "IE",
    alpha3Code: "IRL",
    flag: "assets/flags/Ireland.svg",
    code: "+353",
  },
  {
    name: "Isle of Man",
    alpha2Code: "IM",
    alpha3Code: "IMN",
    flag: "assets/flags/Isle of Man.svg",
    code: "+44",
  },
  {
    name: "Israel",
    alpha2Code: "IL",
    alpha3Code: "ISR",
    flag: "assets/flags/Israel.svg",
    code: "+972",
  },
  {
    name: "Italy",
    alpha2Code: "IT",
    alpha3Code: "ITA",
    flag: "assets/flags/Italy.svg",
    code: "+39",
  },
  {
    name: "Jamaica",
    alpha2Code: "JM",
    alpha3Code: "JAM",
    flag: "assets/flags/Jamaica.svg",
    code: "+1876",
  },
  {
    name: "Japan",
    alpha2Code: "JP",
    alpha3Code: "JPN",
    flag: "assets/flags/Japan.svg",
    code: "+81",
  },
  {
    name: "Jersey",
    alpha2Code: "JE",
    alpha3Code: "JEY",
    flag: "assets/flags/Jersey.svg",
    code: "+44",
  },
  {
    name: "Jordan",
    alpha2Code: "JO",
    alpha3Code: "JOR",
    flag: "assets/flags/Jordan.svg",
    code: "+962",
  },
  {
    name: "Kazakhstan",
    alpha2Code: "KZ",
    alpha3Code: "KAZ",
    flag: "assets/flags/Kazakhstan.svg",
    code: "+76",
  },
  {
    name: "Kenya",
    alpha2Code: "KE",
    alpha3Code: "KEN",
    flag: "assets/flags/Kenya.svg",
    code: "+254",
  },
  {
    name: "Kiribati",
    alpha2Code: "KI",
    alpha3Code: "KIR",
    flag: "assets/flags/Kiribati.svg",
    code: "+686",
  },
  {
    name: "Kuwait",
    alpha2Code: "KW",
    alpha3Code: "KWT",
    flag: "assets/flags/Kuwait.svg",
    code: "+965",
  },
  {
    name: "Kyrgyzstan",
    alpha2Code: "KG",
    alpha3Code: "KGZ",
    flag: "assets/flags/Kyrgyzstan.svg",
    code: "+996",
  },
  {
    name: "Lao People's Democratic Republic",
    alpha2Code: "LA",
    alpha3Code: "LAO",
    flag: "assets/flags/Lao People's Democratic Republic.svg",
    code: "+856",
  },
  {
    name: "Latvia",
    alpha2Code: "LV",
    alpha3Code: "LVA",
    flag: "assets/flags/Latvia.svg",
    code: "+371",
  },
  {
    name: "Lebanon",
    alpha2Code: "LB",
    alpha3Code: "LBN",
    flag: "assets/flags/Lebanon.svg",
    code: "+961",
  },
  {
    name: "Lesotho",
    alpha2Code: "LS",
    alpha3Code: "LSO",
    flag: "assets/flags/Lesotho.svg",
    code: "+266",
  },
  {
    name: "Liberia",
    alpha2Code: "LR",
    alpha3Code: "LBR",
    flag: "assets/flags/Liberia.svg",
    code: "+231",
  },
  {
    name: "Libya",
    alpha2Code: "LY",
    alpha3Code: "LBY",
    flag: "assets/flags/Libya.svg",
    code: "+218",
  },
  {
    name: "Liechtenstein",
    alpha2Code: "LI",
    alpha3Code: "LIE",
    flag: "assets/flags/Liechtenstein.svg",
    code: "+423",
  },
  {
    name: "Lithuania",
    alpha2Code: "LT",
    alpha3Code: "LTU",
    flag: "assets/flags/Lithuania.svg",
    code: "+370",
  },
  {
    name: "Luxembourg",
    alpha2Code: "LU",
    alpha3Code: "LUX",
    flag: "assets/flags/Luxembourg.svg",
    code: "+352",
  },
  {
    name: "Macao",
    alpha2Code: "MO",
    alpha3Code: "MAC",
    flag: "assets/flags/Macao.svg",
    code: "+853",
  },
  {
    name: "Macedonia (the former Yugoslav Republic of)",
    alpha2Code: "MK",
    alpha3Code: "MKD",
    flag: "assets/flags/Macedonia (the former Yugoslav Republic of).svg",
    code: "+389",
  },
  {
    name: "Madagascar",
    alpha2Code: "MG",
    alpha3Code: "MDG",
    flag: "assets/flags/Madagascar.svg",
    code: "+261",
  },
  {
    name: "Malawi",
    alpha2Code: "MW",
    alpha3Code: "MWI",
    flag: "assets/flags/Malawi.svg",
    code: "+265",
  },

  {
    name: "Maldives",
    alpha2Code: "MV",
    alpha3Code: "MDV",
    flag: "assets/flags/Maldives.svg",
    code: "+960",
  },
  {
    name: "Mali",
    alpha2Code: "ML",
    alpha3Code: "MLI",
    flag: "assets/flags/Mali.svg",
    code: "+223",
  },
  {
    name: "Malta",
    alpha2Code: "MT",
    alpha3Code: "MLT",
    flag: "assets/flags/Malta.svg",
    code: "+356",
  },
  {
    name: "Marshall Islands",
    alpha2Code: "MH",
    alpha3Code: "MHL",
    flag: "assets/flags/Marshall Islands.svg",
    code: "+692",
  },
  {
    name: "Martinique",
    alpha2Code: "MQ",
    alpha3Code: "MTQ",
    flag: "assets/flags/Martinique.svg",
    code: "+596",
  },
  {
    name: "Mauritania",
    alpha2Code: "MR",
    alpha3Code: "MRT",
    flag: "assets/flags/Mauritania.svg",
    code: "+222",
  },
  {
    name: "Mauritius",
    alpha2Code: "MU",
    alpha3Code: "MUS",
    flag: "assets/flags/Mauritius.svg",
    code: "+230",
  },
  {
    name: "Mayotte",
    alpha2Code: "YT",
    alpha3Code: "MYT",
    flag: "assets/flags/Mayotte.svg",
    code: "+262",
  },
  {
    name: "Mexico",
    alpha2Code: "MX",
    alpha3Code: "MEX",
    flag: "assets/flags/Mexico.svg",
    code: "+52",
  },
  {
    name: "Micronesia (Federated States of)",
    alpha2Code: "FM",
    alpha3Code: "FSM",
    flag: "assets/flags/Micronesia (Federated States of).svg",
    code: "+691",
  },
  {
    name: "Moldova (Republic of)",
    alpha2Code: "MD",
    alpha3Code: "MDA",
    flag: "assets/flags/Moldova (Republic of).svg",
    code: "+373",
  },
  {
    name: "Monaco",
    alpha2Code: "MC",
    alpha3Code: "MCO",
    flag: "assets/flags/Monaco.svg",
    code: "+377",
  },
  {
    name: "Mongolia",
    alpha2Code: "MN",
    alpha3Code: "MNG",
    flag: "assets/flags/Mongolia.svg",
    code: "+976",
  },
  {
    name: "Montenegro",
    alpha2Code: "ME",
    alpha3Code: "MNE",
    flag: "assets/flags/Montenegro.svg",
    code: "+382",
  },
  {
    name: "Montserrat",
    alpha2Code: "MS",
    alpha3Code: "MSR",
    flag: "assets/flags/Montserrat.svg",
    code: "+1664",
  },
  {
    name: "Morocco",
    alpha2Code: "MA",
    alpha3Code: "MAR",
    flag: "assets/flags/Morocco.svg",
    code: "+212",
  },
  {
    name: "Mozambique",
    alpha2Code: "MZ",
    alpha3Code: "MOZ",
    flag: "assets/flags/Mozambique.svg",
    code: "+258",
  },
  {
    name: "Myanmar",
    alpha2Code: "MM",
    alpha3Code: "MMR",
    flag: "assets/flags/Myanmar.svg",
    code: "+95",
  },
  {
    name: "Namibia",
    alpha2Code: "NA",
    alpha3Code: "NAM",
    flag: "assets/flags/Namibia.svg",
    code: "+264",
  },
  {
    name: "Nauru",
    alpha2Code: "NR",
    alpha3Code: "NRU",
    flag: "assets/flags/Nauru.svg",
    code: "+674",
  },
  {
    name: "Nepal",
    alpha2Code: "NP",
    alpha3Code: "NPL",
    flag: "assets/flags/Nepal.svg",
    code: "+977",
  },
  {
    name: "Netherlands",
    alpha2Code: "NL",
    alpha3Code: "NLD",
    flag: "assets/flags/Netherlands.svg",
    code: "+31",
  },
  {
    name: "New Caledonia",
    alpha2Code: "NC",
    alpha3Code: "NCL",
    flag: "assets/flags/New Caledonia.svg",
    code: "+687",
  },
  {
    name: "New Zealand",
    alpha2Code: "NZ",
    alpha3Code: "NZL",
    flag: "assets/flags/New Zealand.svg",
    code: "+64",
  },
  {
    name: "Nicaragua",
    alpha2Code: "NI",
    alpha3Code: "NIC",
    flag: "assets/flags/Nicaragua.svg",
    code: "+505",
  },
  {
    name: "Niger",
    alpha2Code: "NE",
    alpha3Code: "NER",
    flag: "assets/flags/Niger.svg",
    code: "+227",
  },
  {
    name: "Nigeria",
    alpha2Code: "NG",
    alpha3Code: "NGA",
    flag: "assets/flags/Nigeria.svg",
    code: "+234",
  },
  {
    name: "Niue",
    alpha2Code: "NU",
    alpha3Code: "NIU",
    flag: "assets/flags/Niue.svg",
    code: "+683",
  },
  {
    name: "Norfolk Island",
    alpha2Code: "NF",
    alpha3Code: "NFK",
    flag: "assets/flags/Norfolk Island.svg",
    code: "+672",
  },
  {
    name: "Korea (Democratic People's Republic of)",
    alpha2Code: "KP",
    alpha3Code: "PRK",
    flag: "assets/flags/Korea (Democratic People's Republic of).svg",
    code: "+850",
  },
  {
    name: "Northern Mariana Islands",
    alpha2Code: "MP",
    alpha3Code: "MNP",
    flag: "assets/flags/Northern Mariana Islands.svg",
    code: "+1670",
  },
  {
    name: "Norway",
    alpha2Code: "NO",
    alpha3Code: "NOR",
    flag: "assets/flags/Norway.svg",
    code: "+47",
  },
  {
    name: "Oman",
    alpha2Code: "OM",
    alpha3Code: "OMN",
    flag: "assets/flags/Oman.svg",
    code: "+968",
  },
  {
    name: "Pakistan",
    alpha2Code: "PK",
    alpha3Code: "PAK",
    flag: "assets/flags/Pakistan.svg",
    code: "+92",
  },
  {
    name: "Palau",
    alpha2Code: "PW",
    alpha3Code: "PLW",
    flag: "assets/flags/Palau.svg",
    code: "+680",
  },
  {
    name: "Palestine, State of",
    alpha2Code: "PS",
    alpha3Code: "PSE",
    flag: "assets/flags/Palestine, State of.svg",
    code: "+970",
  },
  {
    name: "Panama",
    alpha2Code: "PA",
    alpha3Code: "PAN",
    flag: "assets/flags/Panama.svg",
    code: "+507",
  },
  {
    name: "Papua New Guinea",
    alpha2Code: "PG",
    alpha3Code: "PNG",
    flag: "assets/flags/Papua New Guinea.svg",
    code: "+675",
  },
  {
    name: "Paraguay",
    alpha2Code: "PY",
    alpha3Code: "PRY",
    flag: "assets/flags/Paraguay.svg",
    code: "+595",
  },
  {
    name: "Peru",
    alpha2Code: "PE",
    alpha3Code: "PER",
    flag: "assets/flags/Peru.svg",
    code: "+51",
  },
  {
    name: "Philippines",
    alpha2Code: "PH",
    alpha3Code: "PHL",
    flag: "assets/flags/Philippines.svg",
    code: "+63",
  },
  {
    name: "Pitcairn",
    alpha2Code: "PN",
    alpha3Code: "PCN",
    flag: "assets/flags/Pitcairn.svg",
    code: "+64",
  },
  {
    name: "Poland",
    alpha2Code: "PL",
    alpha3Code: "POL",
    flag: "assets/flags/Poland.svg",
    code: "+48",
  },
  {
    name: "Portugal",
    alpha2Code: "PT",
    alpha3Code: "PRT",
    flag: "assets/flags/Portugal.svg",
    code: "+351",
  },
  {
    name: "Puerto Rico",
    alpha2Code: "PR",
    alpha3Code: "PRI",
    flag: "assets/flags/Puerto Rico.svg",
    code: "+1787",
  },
  {
    name: "Qatar",
    alpha2Code: "QA",
    alpha3Code: "QAT",
    flag: "assets/flags/Qatar.svg",
    code: "+974",
  },
  {
    name: "Republic of Kosovo",
    alpha2Code: "XK",
    alpha3Code: "KOS",
    flag: "assets/flags/Republic of Kosovo.svg",
    code: "+383",
  },
  {
    name: "Réunion",
    alpha2Code: "RE",
    alpha3Code: "REU",
    flag: "assets/flags/Réunion.svg",
    code: "+262",
  },
  {
    name: "Romania",
    alpha2Code: "RO",
    alpha3Code: "ROU",
    flag: "assets/flags/Romania.svg",
    code: "+40",
  },
  {
    name: "Russian Federation",
    alpha2Code: "RU",
    alpha3Code: "RUS",
    flag: "assets/flags/Russian Federation.svg",
    code: "+7",
  },
  {
    name: "Rwanda",
    alpha2Code: "RW",
    alpha3Code: "RWA",
    flag: "assets/flags/Rwanda.svg",
    code: "+250",
  },
  {
    name: "Saint Barthélemy",
    alpha2Code: "BL",
    alpha3Code: "BLM",
    flag: "assets/flags/Saint Barthélemy.svg",
    code: "+590",
  },
  {
    name: "Saint Helena, Ascension and Tristan da Cunha",
    alpha2Code: "SH",
    alpha3Code: "SHN",
    flag: "assets/flags/Saint Helena, Ascension and Tristan da Cunha.svg",
    code: "+290",
  },
  {
    name: "Saint Kitts and Nevis",
    alpha2Code: "KN",
    alpha3Code: "KNA",
    flag: "assets/flags/Saint Kitts and Nevis.svg",
    code: "+1869",
  },
  {
    name: "Saint Lucia",
    alpha2Code: "LC",
    alpha3Code: "LCA",
    flag: "assets/flags/Saint Lucia.svg",
    code: "+1758",
  },
  {
    name: "Saint Martin (French part)",
    alpha2Code: "MF",
    alpha3Code: "MAF",
    flag: "assets/flags/Saint Martin (French part).svg",
    code: "+590",
  },
  {
    name: "Saint Pierre and Miquelon",
    alpha2Code: "PM",
    alpha3Code: "SPM",
    flag: "assets/flags/Saint Pierre and Miquelon.svg",
    code: "+508",
  },
  {
    name: "Saint Vincent and the Grenadines",
    alpha2Code: "VC",
    alpha3Code: "VCT",
    flag: "assets/flags/Saint Vincent and the Grenadines.svg",
    code: "+1784",
  },
  {
    name: "Samoa",
    alpha2Code: "WS",
    alpha3Code: "WSM",
    flag: "assets/flags/Samoa.svg",
    code: "+685",
  },
  {
    name: "San Marino",
    alpha2Code: "SM",
    alpha3Code: "SMR",
    flag: "assets/flags/San Marino.svg",
    code: "+378",
  },
  {
    name: "Sao Tome and Principe",
    alpha2Code: "ST",
    alpha3Code: "STP",
    flag: "assets/flags/Sao Tome and Principe.svg",
    code: "+239",
  },
  {
    name: "Saudi Arabia",
    alpha2Code: "SA",
    alpha3Code: "SAU",
    flag: "assets/flags/Saudi Arabia.svg",
    code: "+966",
  },
  {
    name: "Senegal",
    alpha2Code: "SN",
    alpha3Code: "SEN",
    flag: "assets/flags/Senegal.svg",
    code: "+221",
  },
  {
    name: "Serbia",
    alpha2Code: "RS",
    alpha3Code: "SRB",
    flag: "assets/flags/Serbia.svg",
    code: "+381",
  },
  {
    name: "Seychelles",
    alpha2Code: "SC",
    alpha3Code: "SYC",
    flag: "assets/flags/Seychelles.svg",
    code: "+248",
  },
  {
    name: "Sierra Leone",
    alpha2Code: "SL",
    alpha3Code: "SLE",
    flag: "assets/flags/Sierra Leone.svg",
    code: "+232",
  },
  {
    name: "Sint Maarten (Dutch part)",
    alpha2Code: "SX",
    alpha3Code: "SXM",
    flag: "assets/flags/Sint Maarten (Dutch part).svg",
    code: "+1721",
  },
  {
    name: "Slovakia",
    alpha2Code: "SK",
    alpha3Code: "SVK",
    flag: "assets/flags/Slovakia.svg",
    code: "+421",
  },
  {
    name: "Slovenia",
    alpha2Code: "SI",
    alpha3Code: "SVN",
    flag: "assets/flags/Slovenia.svg",
    code: "+386",
  },
  {
    name: "Solomon Islands",
    alpha2Code: "SB",
    alpha3Code: "SLB",
    flag: "assets/flags/Solomon Islands.svg",
    code: "+677",
  },
  {
    name: "Somalia",
    alpha2Code: "SO",
    alpha3Code: "SOM",
    flag: "assets/flags/Somalia.svg",
    code: "+252",
  },
  {
    name: "South Africa",
    alpha2Code: "ZA",
    alpha3Code: "ZAF",
    flag: "assets/flags/South Africa.svg",
    code: "+27",
  },
  {
    name: "South Georgia and the South Sandwich Islands",
    alpha2Code: "GS",
    alpha3Code: "SGS",
    flag: "assets/flags/South Georgia and the South Sandwich Islands.svg",
    code: "+500",
  },
  {
    name: "Korea (Republic of)",
    alpha2Code: "KR",
    alpha3Code: "KOR",
    flag: "assets/flags/Korea (Republic of).svg",
    code: "+82",
  },
  {
    name: "South Sudan",
    alpha2Code: "SS",
    alpha3Code: "SSD",
    flag: "assets/flags/South Sudan.svg",
    code: "+211",
  },
  {
    name: "Spain",
    alpha2Code: "ES",
    alpha3Code: "ESP",
    flag: "assets/flags/Spain.svg",
    code: "+34",
  },
  {
    name: "Sri Lanka",
    alpha2Code: "LK",
    alpha3Code: "LKA",
    flag: "assets/flags/Sri Lanka.svg",
    code: "+94",
  },
  {
    name: "Sudan",
    alpha2Code: "SD",
    alpha3Code: "SDN",
    flag: "assets/flags/Sudan.svg",
    code: "+249",
  },
  {
    name: "Suriname",
    alpha2Code: "SR",
    alpha3Code: "SUR",
    flag: "assets/flags/Suriname.svg",
    code: "+597",
  },
  {
    name: "Svalbard and Jan Mayen",
    alpha2Code: "SJ",
    alpha3Code: "SJM",
    flag: "assets/flags/Svalbard and Jan Mayen.svg",
    code: "+4779",
  },
  {
    name: "Swaziland",
    alpha2Code: "SZ",
    alpha3Code: "SWZ",
    flag: "assets/flags/Swaziland.svg",
    code: "+268",
  },
  {
    name: "Sweden",
    alpha2Code: "SE",
    alpha3Code: "SWE",
    flag: "assets/flags/Sweden.svg",
    code: "+46",
  },
  {
    name: "Switzerland",
    alpha2Code: "CH",
    alpha3Code: "CHE",
    flag: "assets/flags/Switzerland.svg",
    code: "+41",
  },
  {
    name: "Syrian Arab Republic",
    alpha2Code: "SY",
    alpha3Code: "SYR",
    flag: "assets/flags/Syrian Arab Republic.svg",
    code: "+963",
  },
  {
    name: "Taiwan",
    alpha2Code: "TW",
    alpha3Code: "TWN",
    flag: "assets/flags/Taiwan.svg",
    code: "+886",
  },
  {
    name: "Tajikistan",
    alpha2Code: "TJ",
    alpha3Code: "TJK",
    flag: "assets/flags/Tajikistan.svg",
    code: "+992",
  },
  {
    name: "Tanzania, United Republic of",
    alpha2Code: "TZ",
    alpha3Code: "TZA",
    flag: "assets/flags/Tanzania, United Republic of.svg",
    code: "+255",
  },
  {
    name: "Thailand",
    alpha2Code: "TH",
    alpha3Code: "THA",
    flag: "assets/flags/Thailand.svg",
    code: "+66",
  },
  {
    name: "Timor-Leste",
    alpha2Code: "TL",
    alpha3Code: "TLS",
    flag: "assets/flags/Timor-Leste.svg",
    code: "+670",
  },
  {
    name: "Togo",
    alpha2Code: "TG",
    alpha3Code: "TGO",
    flag: "assets/flags/Togo.svg",
    code: "+228",
  },
  {
    name: "Tokelau",
    alpha2Code: "TK",
    alpha3Code: "TKL",
    flag: "assets/flags/Tokelau.svg",
    code: "+690",
  },
  {
    name: "Tonga",
    alpha2Code: "TO",
    alpha3Code: "TON",
    flag: "assets/flags/Tonga.svg",
    code: "+676",
  },
  {
    name: "Trinidad and Tobago",
    alpha2Code: "TT",
    alpha3Code: "TTO",
    flag: "assets/flags/Trinidad and Tobago.svg",
    code: "+1868",
  },
  {
    name: "Tunisia",
    alpha2Code: "TN",
    alpha3Code: "TUN",
    flag: "assets/flags/Tunisia.svg",
    code: "+216",
  },
  {
    name: "Turkey",
    alpha2Code: "TR",
    alpha3Code: "TUR",
    flag: "assets/flags/Turkey.svg",
    code: "+90",
  },
  {
    name: "Turkmenistan",
    alpha2Code: "TM",
    alpha3Code: "TKM",
    flag: "assets/flags/Turkmenistan.svg",
    code: "+993",
  },
  {
    name: "Turks and Caicos Islands",
    alpha2Code: "TC",
    alpha3Code: "TCA",
    flag: "assets/flags/Turks and Caicos Islands.svg",
    code: "+1649",
  },
  {
    name: "Tuvalu",
    alpha2Code: "TV",
    alpha3Code: "TUV",
    flag: "assets/flags/Tuvalu.svg",
    code: "+688",
  },
  {
    name: "Uganda",
    alpha2Code: "UG",
    alpha3Code: "UGA",
    flag: "assets/flags/Uganda.svg",
    code: "+256",
  },
  {
    name: "Ukraine",
    alpha2Code: "UA",
    alpha3Code: "UKR",
    flag: "assets/flags/Ukraine.svg",
    code: "+380",
  },
  {
    name: "United Arab Emirates",
    alpha2Code: "AE",
    alpha3Code: "ARE",
    flag: "assets/flags/United Arab Emirates.svg",
    code: "+971",
  },
  {
    name: "United Kingdom of Great Britain and Northern Ireland",
    alpha2Code: "GB",
    alpha3Code: "GBR",
    flag: "assets/flags/United Kingdom of Great Britain and Northern Ireland.svg",
    code: "+44",
  },
  {
    name: "United States of America",
    alpha2Code: "US",
    alpha3Code: "USA",
    flag: "assets/flags/United States of America.svg",
    code: "+1",
  },
  {
    name: "Uruguay",
    alpha2Code: "UY",
    alpha3Code: "URY",
    flag: "assets/flags/Uruguay.svg",
    code: "+598",
  },
  {
    name: "Uzbekistan",
    alpha2Code: "UZ",
    alpha3Code: "UZB",
    flag: "assets/flags/Uzbekistan.svg",
    code: "+998",
  },
  {
    name: "Vanuatu",
    alpha2Code: "VU",
    alpha3Code: "VUT",
    flag: "assets/flags/Vanuatu.svg",
    code: "+678",
  },
  {
    name: "Venezuela (Bolivarian Republic of)",
    alpha2Code: "VE",
    alpha3Code: "VEN",
    flag: "assets/flags/Venezuela (Bolivarian Republic of).svg",
    code: "+58",
  },
  {
    name: "Viet Nam",
    alpha2Code: "VN",
    alpha3Code: "VNM",
    flag: "assets/flags/Viet Nam.svg",
    code: "+84",
  },
  {
    name: "Wallis and Futuna",
    alpha2Code: "WF",
    alpha3Code: "WLF",
    flag: "assets/flags/Wallis and Futuna.svg",
    code: "+681",
  },
  {
    name: "Western Sahara",
    alpha2Code: "EH",
    alpha3Code: "ESH",
    flag: "assets/flags/Western Sahara.svg",
    code: "+212",
  },
  {
    name: "Yemen",
    alpha2Code: "YE",
    alpha3Code: "YEM",
    flag: "assets/flags/Yemen.svg",
    code: "+967",
  },
  {
    name: "Zambia",
    alpha2Code: "ZM",
    alpha3Code: "ZMB",
    flag: "assets/flags/Zambia.svg",
    code: "+260",
  },
  {
    name: "Zimbabwe",
    alpha2Code: "ZW",
    alpha3Code: "ZWE",
    flag: "assets/flags/Zimbabwe.svg",
    code: "+263",
  },
];
