import { IValidation } from "../models/validation.interface";

export const VALIDATION_CRITERIA: IValidation = {
  emailMaxLength: 100,
  passwordMinLength: 8,
  passwordMaxLength: 15,
  nameMinLength: 2,
  nameMaxLength: 100,
  phoneMinLength: 8,
  phoneMaxLength: 14,
  descriptionMinLength: 3,
  descriptionMaxLength: 500,
  descriptionMaxLength400: 400,
  descriptionMaxLength1200: 1200,
  priceMinLength: 1,
  priceMaxLength: 10,
  minFloor: 0,
  maxFloor: 20,
  minArea: 100,
  maxArea: 10000,
  houseNumberMinLength: 1,
  houseNumberMaxLength: 100,
  streetMinLength: 3,
  streetMaxLength: 100,
  zipcodeMinLength: 2,
  zipcodeMaxLength: 16,
  taxNumberMinLength: 3,
  taxNumberMaxLength: 40,
  regNumberMinLength: 3,
  regNumberMaxLength: 40,
  landmarkMinLength: 3,
  landmarkMaxLength: 140,
  bioMinLength: 3,
  bioMaxLength: 140,
  addressMinLength: 3,
  addressMaxLength: 200,
  phoneNumber: 10,
  subjectMaxLength: 250,
  maxvacancies: 2,
  uenMinLength: 9,
  uenMaxLength: 10,
  maxinviteTitleLength:100,
  mininviteTitleLength:2,
  mininviteMsgLength:3,
  maxinviteMsgLength:500,
};
